// Full country/nationality list with ISO-2 codes
export const NATIONALITIES: { code: string; label: string }[] = [
  { code: "OM", label: "Omani" },
  { code: "AE", label: "Emirati" },
  { code: "SA", label: "Saudi Arabian" },
  { code: "KW", label: "Kuwaiti" },
  { code: "QA", label: "Qatari" },
  { code: "BH", label: "Bahraini" },
  { code: "JO", label: "Jordanian" },
  { code: "EG", label: "Egyptian" },
  { code: "LB", label: "Lebanese" },
  { code: "SY", label: "Syrian" },
  { code: "IQ", label: "Iraqi" },
  { code: "YE", label: "Yemeni" },
  { code: "PS", label: "Palestinian" },
  { code: "SD", label: "Sudanese" },
  { code: "MA", label: "Moroccan" },
  { code: "TN", label: "Tunisian" },
  { code: "DZ", label: "Algerian" },
  { code: "LY", label: "Libyan" },
  { code: "SO", label: "Somali" },
  { code: "ET", label: "Ethiopian" },
  { code: "KE", label: "Kenyan" },
  { code: "TZ", label: "Tanzanian" },
  { code: "UG", label: "Ugandan" },
  { code: "GH", label: "Ghanaian" },
  { code: "NG", label: "Nigerian" },
  { code: "ZA", label: "South African" },
  { code: "IN", label: "Indian" },
  { code: "PK", label: "Pakistani" },
  { code: "BD", label: "Bangladeshi" },
  { code: "LK", label: "Sri Lankan" },
  { code: "NP", label: "Nepali" },
  { code: "PH", label: "Filipino" },
  { code: "ID", label: "Indonesian" },
  { code: "MY", label: "Malaysian" },
  { code: "TH", label: "Thai" },
  { code: "VN", label: "Vietnamese" },
  { code: "CN", label: "Chinese" },
  { code: "KR", label: "South Korean" },
  { code: "JP", label: "Japanese" },
  { code: "TR", label: "Turkish" },
  { code: "IR", label: "Iranian" },
  { code: "AF", label: "Afghan" },
  { code: "GB", label: "British" },
  { code: "US", label: "American" },
  { code: "CA", label: "Canadian" },
  { code: "AU", label: "Australian" },
  { code: "NZ", label: "New Zealander" },
  { code: "DE", label: "German" },
  { code: "FR", label: "French" },
  { code: "IT", label: "Italian" },
  { code: "ES", label: "Spanish" },
  { code: "NL", label: "Dutch" },
  { code: "BE", label: "Belgian" },
  { code: "CH", label: "Swiss" },
  { code: "AT", label: "Austrian" },
  { code: "SE", label: "Swedish" },
  { code: "NO", label: "Norwegian" },
  { code: "DK", label: "Danish" },
  { code: "FI", label: "Finnish" },
  { code: "PL", label: "Polish" },
  { code: "RU", label: "Russian" },
  { code: "UA", label: "Ukrainian" },
  { code: "RO", label: "Romanian" },
  { code: "GR", label: "Greek" },
  { code: "PT", label: "Portuguese" },
  { code: "BR", label: "Brazilian" },
  { code: "MX", label: "Mexican" },
  { code: "AR", label: "Argentine" },
  { code: "CL", label: "Chilean" },
  { code: "CO", label: "Colombian" },
  { code: "ZW", label: "Zimbabwean" },
  { code: "ZM", label: "Zambian" },
  { code: "MU", label: "Mauritian" },
  { code: "MG", label: "Malagasy" },
  { code: "CM", label: "Cameroonian" },
  { code: "SN", label: "Senegalese" },
  { code: "CI", label: "Ivorian" },
  { code: "MM", label: "Burmese" },
  { code: "KH", label: "Cambodian" },
  { code: "LA", label: "Laotian" },
  { code: "MN", label: "Mongolian" },
  { code: "KZ", label: "Kazakhstani" },
  { code: "UZ", label: "Uzbekistani" },
  { code: "AZ", label: "Azerbaijani" },
  { code: "GE", label: "Georgian" },
  { code: "AM", label: "Armenian" },
  { code: "Other", label: "Other" },
];

export const PROFESSIONS: string[] = [
  "Accountant", "Administrative Assistant", "Architect", "Auditor",
  "Business Analyst", "Civil Engineer", "Clerk", "Construction Worker",
  "Customer Service Representative", "Data Analyst", "Doctor",
  "Driver", "Electrical Engineer", "Finance Manager", "General Manager",
  "HR Manager", "HR Officer", "IT Engineer", "IT Manager",
  "Lawyer", "Logistics Coordinator", "Maintenance Technician",
  "Marketing Manager", "Mechanical Engineer", "Nurse", "Office Manager",
  "Operations Manager", "Pharmacist", "PRO Officer", "Project Manager",
  "Quality Control Inspector", "Receptionist", "Safety Officer",
  "Sales Executive", "Sales Manager", "Secretary", "Security Guard",
  "Site Engineer", "Software Developer", "Supervisor", "Teacher",
  "Technician", "Warehouse Supervisor", "Other",
];
