import { z } from "zod";
import { canAccessGlobalAdminProcedures } from "@shared/rbac";
import { protectedProcedure, router } from "../_core/trpc";
import { TRPCError } from "@trpc/server";
import { getDb, getUserCompany } from "../db";
import { eq, and, gte, lte, inArray, desc } from "drizzle-orm";
import {
  companies, proBillingCycles, omaniProOfficers, officerCompanyAssignments,
  officerPayouts, complianceCertificates, employees, workPermits,
  payrollRuns, payrollLineItems, governmentServiceCases,
} from "../../drizzle/schema";
import { storagePut } from "../storage";
import PDFDocument from "pdfkit";

// ── Helper: generate PDF buffer from a builder function ──────────────────────
async function buildPdf(builder: (doc: PDFKit.PDFDocument) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    builder(doc);
    doc.end();
  });
}

// ── Helper: page header ───────────────────────────────────────────────────────
function addHeader(doc: PDFKit.PDFDocument, title: string, subtitle?: string) {
  doc.rect(0, 0, doc.page.width, 80).fill("#1a1a2e");
  doc.fillColor("#e8a020").fontSize(20).font("Helvetica-Bold").text("SmartPRO", 50, 20);
  doc.fillColor("#ffffff").fontSize(10).font("Helvetica").text("Business Services Hub", 50, 44);
  doc.fillColor("#ffffff").fontSize(14).font("Helvetica-Bold").text(title, 200, 28, { align: "right", width: doc.page.width - 250 });
  if (subtitle) doc.fillColor("#cccccc").fontSize(9).font("Helvetica").text(subtitle, 200, 48, { align: "right", width: doc.page.width - 250 });
  doc.fillColor("#000000");
  doc.moveDown(3);
}

// ── Helper: section heading ───────────────────────────────────────────────────
function sectionHeading(doc: PDFKit.PDFDocument, text: string) {
  doc.moveDown(0.5);
  doc.rect(50, doc.y, doc.page.width - 100, 22).fill("#f0f0f0");
  doc.fillColor("#1a1a2e").fontSize(11).font("Helvetica-Bold").text(text, 56, doc.y - 18);
  doc.fillColor("#000000").font("Helvetica").fontSize(9);
  doc.moveDown(0.8);
}

// ── Helper: table row ─────────────────────────────────────────────────────────
function tableRow(doc: PDFKit.PDFDocument, cols: string[], widths: number[], x: number, shade: boolean) {
  if (shade) doc.rect(x, doc.y - 2, widths.reduce((a, b) => a + b, 0), 16).fill("#f9f9f9");
  doc.fillColor("#333333").fontSize(8).font("Helvetica");
  let cx = x;
  cols.forEach((col, i) => {
    doc.text(col, cx + 3, doc.y - 14, { width: widths[i] - 6, ellipsis: true });
    cx += widths[i];
  });
  doc.fillColor("#000000");
  doc.moveDown(0.3);
}

// ── Helper: table header ──────────────────────────────────────────────────────
function tableHeader(doc: PDFKit.PDFDocument, cols: string[], widths: number[], x: number) {
  doc.rect(x, doc.y, widths.reduce((a, b) => a + b, 0), 18).fill("#1a1a2e");
  doc.fillColor("#ffffff").fontSize(8).font("Helvetica-Bold");
  let cx = x;
  cols.forEach((col, i) => {
    doc.text(col, cx + 3, doc.y - 14, { width: widths[i] - 6 });
    cx += widths[i];
  });
  doc.fillColor("#000000").font("Helvetica");
  doc.moveDown(0.5);
}

// ── Helper: footer ────────────────────────────────────────────────────────────
function addFooter(doc: PDFKit.PDFDocument) {
  const y = doc.page.height - 40;
  doc.rect(0, y, doc.page.width, 40).fill("#f5f5f5");
  doc.fillColor("#888888").fontSize(7).font("Helvetica")
    .text(`Generated by SmartPRO Business Services Hub · ${new Date().toLocaleString("en-OM", { timeZone: "Asia/Muscat" })} AST`, 50, y + 8)
    .text("Confidential — For internal use only", 50, y + 20);
}

// ── Router ────────────────────────────────────────────────────────────────────
export const reportsRouter = router({

  // ── Billing Summary Report ──────────────────────────────────────────────────
  generateBillingSummary: protectedProcedure
    .input(z.object({ month: z.number().min(1).max(12), year: z.number().min(2020) }))
    .mutation(async ({ ctx, input }) => {
      const membership = await getUserCompany(ctx.user.id);
      if (!membership?.company?.id) {
        throw new TRPCError({ code: "NOT_FOUND", message: "No company found" });
      }
      const companyId = membership.company.id;
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "DB unavailable" });

      const [company] = await db.select().from(companies).where(eq(companies.id, companyId)).limit(1);

      // Get billing cycles for this month/year
      const cycles = await db.select({
        id: proBillingCycles.id,
        invoiceNumber: proBillingCycles.invoiceNumber,
        amountOmr: proBillingCycles.amountOmr,
        status: proBillingCycles.status,
        paidAt: proBillingCycles.paidAt,
        officerName: omaniProOfficers.fullName,
        officerPasiId: omaniProOfficers.pasiNumber,
      }).from(proBillingCycles)
        .leftJoin(omaniProOfficers, eq(proBillingCycles.officerId, omaniProOfficers.id))
        .where(and(
          eq(proBillingCycles.companyId, companyId),
          eq(proBillingCycles.billingMonth, input.month),
          eq(proBillingCycles.billingYear, input.year),
        ));

      const totalAmount = cycles.reduce((s, c) => s + Number(c.amountOmr ?? 0), 0);
      const paidAmount = cycles.filter(c => c.status === "paid").reduce((s, c) => s + Number(c.amountOmr ?? 0), 0);
      const monthName = new Date(input.year, input.month - 1).toLocaleString("en-OM", { month: "long" });

      const pdfBuffer = await buildPdf((doc) => {
        addHeader(doc, "Billing Summary Report", `${monthName} ${input.year}`);

        // Company info box
        doc.rect(50, doc.y, doc.page.width - 100, 50).stroke("#dddddd");
        doc.fontSize(10).font("Helvetica-Bold").text("Billed To:", 60, doc.y - 46);
        doc.font("Helvetica").fontSize(9).text(company?.name ?? "—", 60, doc.y - 32);
        doc.text(`CR: ${company?.registrationNumber ?? "—"}  ·  Period: ${monthName} ${input.year}`, 60, doc.y - 20);
        doc.moveDown(2.5);

        // Summary KPIs
        sectionHeading(doc, "Summary");
        const kpis = [
          ["Total Invoices", String(cycles.length)],
          ["Total Amount", `OMR ${totalAmount.toFixed(3)}`],
          ["Paid", `OMR ${paidAmount.toFixed(3)}`],
          ["Outstanding", `OMR ${(totalAmount - paidAmount).toFixed(3)}`],
        ];
        kpis.forEach(([k, v], i) => {
          doc.font("Helvetica-Bold").fontSize(9).text(k + ":", 60 + (i % 2) * 220, doc.y - (i % 2 === 0 && i > 0 ? 0 : 0));
          doc.font("Helvetica").text(v, 160 + (i % 2) * 220, doc.y - 12);
          if (i % 2 === 1) doc.moveDown(0.5);
        });
        doc.moveDown(1);

        // Invoice table
        sectionHeading(doc, "Invoice Details");
        const cols = ["Invoice #", "Officer", "PASI ID", "Amount (OMR)", "Status", "Paid Date"];
        const widths = [90, 110, 80, 80, 60, 75];
        tableHeader(doc, cols, widths, 50);
        cycles.forEach((c, i) => {
          tableRow(doc, [
            c.invoiceNumber ?? "—",
            c.officerName ?? "—",
            c.officerPasiId ?? "—",
            Number(c.amountOmr ?? 0).toFixed(3),
            (c.status ?? "pending").toUpperCase(),
            c.paidAt ? new Date(c.paidAt).toLocaleDateString("en-OM") : "—",
          ], widths, 50, i % 2 === 0);
        });

        addFooter(doc);
      });

      const key = `reports/billing/${companyId}-${input.year}-${String(input.month).padStart(2, "0")}-${Date.now()}.pdf`;
      const { url } = await storagePut(key, pdfBuffer, "application/pdf");
      return { url, filename: `billing-summary-${monthName}-${input.year}.pdf` };
    }),

  // ── Payslip Report ──────────────────────────────────────────────────────────
  generatePayslip: protectedProcedure
    .input(z.object({ runId: z.number(), employeeId: z.number() }))
    .mutation(async ({ ctx, input }) => {
      const membership = await getUserCompany(ctx.user.id);
      if (!membership?.company?.id) {
        throw new TRPCError({ code: "NOT_FOUND", message: "No company found" });
      }
      const companyId = membership.company.id;
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "DB unavailable" });

      const [run] = await db.select().from(payrollRuns)
        .where(and(eq(payrollRuns.id, input.runId), eq(payrollRuns.companyId, companyId))).limit(1);
      if (!run) throw new TRPCError({ code: "NOT_FOUND", message: "Payroll run not found" });

      const [emp] = await db.select().from(employees)
        .where(and(eq(employees.id, input.employeeId), eq(employees.companyId, companyId))).limit(1);
      if (!emp) throw new TRPCError({ code: "NOT_FOUND", message: "Employee not found" });

      const lineItems = await db
        .select()
        .from(payrollLineItems)
        .where(
          and(
            eq(payrollLineItems.payrollRunId, input.runId),
            eq(payrollLineItems.employeeId, input.employeeId),
            eq(payrollLineItems.companyId, companyId),
          ),
        );

      const [company] = await db.select().from(companies).where(eq(companies.id, companyId)).limit(1);

      // payrollLineItems has flat columns: grossSalary, totalDeductions, netSalary, etc.
      const totalEarnings = lineItems.reduce((s, l) => s + Number(l.grossSalary ?? 0), 0);
      const totalDeductions = lineItems.reduce((s, l) => s + Number(l.totalDeductions ?? 0), 0);
      const netPay = lineItems.reduce((s, l) => s + Number(l.netSalary ?? 0), 0);
      const monthName = new Date(run.periodYear, run.periodMonth - 1).toLocaleString("en-OM", { month: "long" });

      const pdfBuffer = await buildPdf((doc) => {
        addHeader(doc, "Payslip", `${monthName} ${run.periodYear}`);

        // Employee & company info
        doc.rect(50, doc.y, doc.page.width - 100, 65).stroke("#dddddd");
        const infoY = doc.y - 61;
        doc.fontSize(9).font("Helvetica-Bold").text("Employee:", 60, infoY);
        doc.font("Helvetica").text(`${emp.firstName} ${emp.lastName}`, 60, infoY + 13);
        doc.text(`ID: ${emp.employeeNumber ?? emp.id}  ·  ${emp.position ?? "—"}`, 60, infoY + 25);
        doc.text(`Nationality: ${emp.nationality ?? "—"}`, 60, infoY + 37);
        doc.font("Helvetica-Bold").text("Employer:", 280, infoY);
        doc.font("Helvetica").text(company?.name ?? "—", 280, infoY + 13);
        doc.text(`CR: ${(company as any)?.registrationNumber ?? "—"}`, 280, infoY + 25);
        doc.text(`Pay Period: ${monthName} ${run.periodYear}`, 280, infoY + 37);
        doc.moveDown(3.5);

        // Earnings breakdown
        sectionHeading(doc, "Earnings");
        tableHeader(doc, ["Description", "Amount (OMR)"], [350, 95], 50);
        lineItems.forEach((l, i) => {
          const rows = [
            ["Basic Salary", Number(l.basicSalary ?? 0)],
            ["Housing Allowance", Number(l.housingAllowance ?? 0)],
            ["Transport Allowance", Number(l.transportAllowance ?? 0)],
            ["Other Allowances", Number(l.otherAllowances ?? 0)],
            ["Overtime Pay", Number(l.overtimePay ?? 0)],
          ] as [string, number][];
          rows.filter(([, v]) => v > 0).forEach(([desc, val], ri) =>
            tableRow(doc, [desc, val.toFixed(3)], [350, 95], 50, (i + ri) % 2 === 0)
          );
        });
        doc.font("Helvetica-Bold").fontSize(9).text("Total Earnings:", 200, doc.y + 4);
        doc.text(`OMR ${totalEarnings.toFixed(3)}`, 350, doc.y - 12, { align: "right", width: 95 });
        doc.moveDown(1);

        // Deductions breakdown
        sectionHeading(doc, "Deductions");
        const hasDeductions = lineItems.some(l => Number(l.totalDeductions ?? 0) > 0);
        if (!hasDeductions) {
          doc.font("Helvetica").fontSize(8).fillColor("#888888").text("No deductions this period.", 60, doc.y);
          doc.fillColor("#000000").moveDown(0.5);
        } else {
          tableHeader(doc, ["Description", "Amount (OMR)"], [350, 95], 50);
          lineItems.forEach((l, i) => {
            const rows = [
              ["PASI Deduction", Number(l.pasiDeduction ?? 0)],
              ["Income Tax", Number(l.incomeTax ?? 0)],
              ["Loan Deduction", Number(l.loanDeduction ?? 0)],
              ["Absence Deduction", Number(l.absenceDeduction ?? 0)],
              ["Other Deductions", Number(l.otherDeductions ?? 0)],
            ] as [string, number][];
            rows.filter(([, v]) => v > 0).forEach(([desc, val], ri) =>
              tableRow(doc, [desc, val.toFixed(3)], [350, 95], 50, (i + ri) % 2 === 0)
            );
          });
          doc.font("Helvetica-Bold").fontSize(9).text("Total Deductions:", 200, doc.y + 4);
          doc.text(`OMR ${totalDeductions.toFixed(3)}`, 350, doc.y - 12, { align: "right", width: 95 });
        }
        doc.moveDown(1);

        // Net pay box
        doc.rect(50, doc.y, doc.page.width - 100, 36).fill("#1a1a2e");
        doc.fillColor("#e8a020").fontSize(13).font("Helvetica-Bold").text("NET PAY", 60, doc.y - 30);
        doc.fillColor("#ffffff").fontSize(16).text(`OMR ${netPay.toFixed(3)}`, 0, doc.y - 30, { align: "right", width: doc.page.width - 60 });
        doc.fillColor("#000000").moveDown(2);

        addFooter(doc);
      });

      const key = `reports/payslips/${companyId}-${emp.id}-${run.periodYear}-${run.periodMonth}-${Date.now()}.pdf`;
      const { url } = await storagePut(key, pdfBuffer, "application/pdf");
      return { url, filename: `payslip-${emp.firstName}-${emp.lastName}-${monthName}-${run.periodYear}.pdf` };
    }),

  // ── Workforce Report ────────────────────────────────────────────────────────
  generateWorkforceReport: protectedProcedure
    .input(z.object({ companyId: z.number().optional() }))
    .mutation(async ({ ctx, input }) => {
      const membership = await getUserCompany(ctx.user.id);
      const memberCompanyId = membership?.company?.id;
      let companyId: number;
      if (canAccessGlobalAdminProcedures(ctx.user)) {
        companyId = input.companyId ?? memberCompanyId!;
        if (!companyId) throw new TRPCError({ code: "NOT_FOUND", message: "No company found" });
      } else {
        if (!memberCompanyId) throw new TRPCError({ code: "NOT_FOUND", message: "No company found" });
        if (input.companyId != null && input.companyId !== memberCompanyId) {
          throw new TRPCError({ code: "NOT_FOUND", message: "Report not found" });
        }
        companyId = memberCompanyId;
      }

      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "DB unavailable" });

      const [company] = await db.select().from(companies).where(eq(companies.id, companyId)).limit(1);

      const empList = await db.select().from(employees).where(eq(employees.companyId, companyId));
      const permits = await db.select().from(workPermits).where(eq(workPermits.companyId, companyId));
      const cases = await db.select().from(governmentServiceCases).where(eq(governmentServiceCases.companyId, companyId));

      const now = Date.now();
      const expiringSoon = permits.filter(p => {
        if (!p.expiryDate) return false;
        const days = (new Date(p.expiryDate).getTime() - now) / 86400000;
        return days >= 0 && days <= 90;
      });

      const pdfBuffer = await buildPdf((doc) => {
        addHeader(doc, "Workforce Report", `Generated ${new Date().toLocaleDateString("en-OM")}`);

        // Company header
        doc.fontSize(12).font("Helvetica-Bold").text(company?.name ?? "—", 50, doc.y);
        doc.fontSize(9).font("Helvetica").fillColor("#666666").text(`CR: ${(company as any)?.registrationNumber ?? "—"}  ·  Report Date: ${new Date().toLocaleDateString("en-OM", { timeZone: "Asia/Muscat" })}`, 50, doc.y + 2);
        doc.fillColor("#000000").moveDown(1.5);

        // KPI summary
        sectionHeading(doc, "Workforce Summary");
        const kpis = [
          ["Total Employees", String(empList.length)],
          ["Active Employees", String(empList.filter(e => e.status === "active").length)],
          ["Work Permits", String(permits.length)],
          ["Expiring ≤90 Days", String(expiringSoon.length)],
          ["Open Cases", String(cases.filter(c => !["completed", "closed", "rejected"].includes(c.caseStatus ?? "")).length)],
          ["Closed Cases", String(cases.filter(c => ["completed", "closed"].includes(c.caseStatus ?? "")).length)],
        ];
        kpis.forEach(([k, v], i) => {
          const col = i % 3;
          const row = Math.floor(i / 3);
          const x = 60 + col * 160;
          const y = doc.y - (col === 0 && row > 0 ? 0 : 0);
          doc.font("Helvetica-Bold").fontSize(9).text(k, x, doc.y - (i > 0 && col === 0 ? 0 : 0));
          doc.font("Helvetica").fontSize(18).fillColor("#1a1a2e").text(v, x, doc.y - 2);
          doc.fillColor("#000000");
          if (col === 2) doc.moveDown(2.5);
        });
        doc.moveDown(1);

        // Employee list
        sectionHeading(doc, "Employee Roster");
        tableHeader(doc, ["Name", "Job Title", "Nationality", "Status", "Join Date"], [140, 110, 90, 70, 85], 50);
        empList.slice(0, 40).forEach((e, i) => tableRow(doc, [
          `${e.firstName} ${e.lastName}`,
          e.position ?? "—",
          e.nationality ?? "—",
          (e.status ?? "active").toUpperCase(),
          e.hireDate ? new Date(e.hireDate).toLocaleDateString("en-OM") : "—",
        ], [140, 110, 90, 70, 85], 50, i % 2 === 0));
        if (empList.length > 40) {
          doc.fontSize(8).fillColor("#888888").text(`... and ${empList.length - 40} more employees`, 60, doc.y + 4);
          doc.fillColor("#000000");
        }
        doc.moveDown(1);

        // Expiring permits
        if (expiringSoon.length > 0) {
          sectionHeading(doc, "Work Permits Expiring Within 90 Days");
          tableHeader(doc, ["Permit #", "Employee ID", "Type", "Expiry Date", "Days Left"], [110, 100, 100, 90, 95], 50);
          expiringSoon.slice(0, 20).forEach((p, i) => {
            const days = Math.ceil((new Date(p.expiryDate!).getTime() - now) / 86400000);
            tableRow(doc, [
            p.workPermitNumber ?? "—",
            String(p.employeeId ?? "—"),
            (p as any).permitCategory ?? "work_permit",
              new Date(p.expiryDate!).toLocaleDateString("en-OM"),
              `${days} days`,
            ], [110, 100, 100, 90, 95], 50, i % 2 === 0);
          });
        }

        addFooter(doc);
      });

      const key = `reports/workforce/${companyId}-${Date.now()}.pdf`;
      const { url } = await storagePut(key, pdfBuffer, "application/pdf");
      return { url, filename: `workforce-report-${company?.name?.replace(/\s+/g, "-") ?? companyId}-${new Date().toISOString().slice(0, 10)}.pdf` };
    }),

  // ── Compliance Certificate Report ───────────────────────────────────────────
  generateComplianceReport: protectedProcedure
    .input(z.object({ month: z.number().min(1).max(12), year: z.number().min(2020) }))
    .mutation(async ({ ctx, input }) => {
      const membership = await getUserCompany(ctx.user.id);
      if (!membership?.company?.id) {
        throw new TRPCError({ code: "NOT_FOUND", message: "No company found" });
      }
      const companyId = membership.company.id;
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "DB unavailable" });

      const [company] = await db.select().from(companies).where(eq(companies.id, companyId)).limit(1);

      // Get all certificates for this company/month
      const certs = await db.select({
        id: complianceCertificates.id,
        certificateNumber: complianceCertificates.certificateNumber,
        generatedAt: complianceCertificates.generatedAt,
        pdfUrl: complianceCertificates.pdfUrl,
        officerName: omaniProOfficers.fullName,
        officerPasiId: omaniProOfficers.pasiNumber,
      }).from(complianceCertificates)
        .leftJoin(omaniProOfficers, eq(complianceCertificates.officerId, omaniProOfficers.id))
        .where(and(
          eq(complianceCertificates.companyId, companyId),
          eq(complianceCertificates.periodMonth, input.month),
          eq(complianceCertificates.periodYear, input.year),
        ));

      const monthName = new Date(input.year, input.month - 1).toLocaleString("en-OM", { month: "long" });

      const pdfBuffer = await buildPdf((doc) => {
        addHeader(doc, "MoL Compliance Report", `${monthName} ${input.year}`);

        doc.fontSize(9).font("Helvetica").fillColor("#666666")
          .text(`This report confirms that the following Omani PRO Officers are assigned and compliant for ${monthName} ${input.year}.`, 50, doc.y, { width: doc.page.width - 100 });
        doc.fillColor("#000000").moveDown(1);

        // Company info
        doc.rect(50, doc.y, doc.page.width - 100, 45).stroke("#dddddd");
        const cy = doc.y - 41;
        doc.font("Helvetica-Bold").fontSize(9).text("Company:", 60, cy);
        doc.font("Helvetica").text(company?.name ?? "—", 60, cy + 13);
        doc.text(`CR Number: ${(company as any)?.registrationNumber ?? "—"}`, 60, cy + 25);
        doc.font("Helvetica-Bold").text("Compliance Period:", 280, cy);
        doc.font("Helvetica").text(`${monthName} ${input.year}`, 280, cy + 13);
        doc.text(`Certificates Issued: ${certs.length}`, 280, cy + 25);
        doc.moveDown(2.5);

        sectionHeading(doc, "Compliance Certificates Issued");
        tableHeader(doc, ["Certificate #", "Officer Name", "PASI ID", "Issued Date", "Document"], [130, 130, 90, 90, 55], 50);
        certs.forEach((c, i) => tableRow(doc, [
          c.certificateNumber ?? "—",
          c.officerName ?? "—",
          c.officerPasiId ?? "—",
          c.generatedAt ? new Date(c.generatedAt).toLocaleDateString("en-OM") : "—",
          c.pdfUrl ? "Available" : "Pending",
        ], [130, 130, 90, 90, 55], 50, i % 2 === 0));

        if (certs.length === 0) {
          doc.fontSize(9).fillColor("#888888").text("No compliance certificates issued for this period.", 60, doc.y);
          doc.fillColor("#000000");
        }

        doc.moveDown(2);
        doc.rect(50, doc.y, doc.page.width - 100, 50).stroke("#dddddd");
        const sigY = doc.y - 46;
        doc.fontSize(8).font("Helvetica").text("Authorised Signature:", 60, sigY + 5);
        doc.text("_________________________", 60, sigY + 18);
        doc.text("Date: ___________________", 60, sigY + 32);
        doc.text("Company Stamp:", 280, sigY + 5);
        doc.rect(280, sigY + 18, 120, 25).stroke("#cccccc");

        addFooter(doc);
      });

      const key = `reports/compliance/${companyId}-${input.year}-${String(input.month).padStart(2, "0")}-${Date.now()}.pdf`;
      const { url } = await storagePut(key, pdfBuffer, "application/pdf");
      return { url, filename: `compliance-report-${monthName}-${input.year}.pdf` };
    }),

  // ── Officer Payout Report ───────────────────────────────────────────────────
  generateOfficerPayoutReport: protectedProcedure
    .input(z.object({ officerId: z.number(), month: z.number().min(1).max(12), year: z.number().min(2020) }))
    .mutation(async ({ ctx, input }) => {
      if (!canAccessGlobalAdminProcedures(ctx.user)) {
        throw new TRPCError({ code: "FORBIDDEN", message: "Platform access required" });
      }
      const db = await getDb();
      if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "DB unavailable" });

      const [officer] = await db.select().from(omaniProOfficers)
        .where(eq(omaniProOfficers.id, input.officerId)).limit(1);
      if (!officer) throw new TRPCError({ code: "NOT_FOUND", message: "Officer not found" });

      const payouts = await db.select().from(officerPayouts)
        .where(and(
          eq(officerPayouts.officerId, input.officerId),
          eq(officerPayouts.payoutMonth, input.month),
          eq(officerPayouts.payoutYear, input.year),
        ));

      const assignments = await db.select({
        id: officerCompanyAssignments.id,
        companyName: companies.name,
        crNumber: companies.registrationNumber,
        track: officerCompanyAssignments.status, // use status as proxy; actual track is on officer
        startDate: officerCompanyAssignments.assignedAt,
        status: officerCompanyAssignments.status,
      }).from(officerCompanyAssignments)
        .leftJoin(companies, eq(officerCompanyAssignments.companyId, companies.id))
        .where(and(eq(officerCompanyAssignments.officerId, input.officerId), eq(officerCompanyAssignments.status, "active")));

      const monthName = new Date(input.year, input.month - 1).toLocaleString("en-OM", { month: "long" });
      const totalNet = payouts.reduce((s, p) => s + Number(p.netOmr ?? 0), 0);

      const pdfBuffer = await buildPdf((doc) => {
        addHeader(doc, "Officer Payout Statement", `${monthName} ${input.year}`);

        // Officer info
        doc.rect(50, doc.y, doc.page.width - 100, 55).stroke("#dddddd");
        const oy = doc.y - 51;
        doc.font("Helvetica-Bold").fontSize(10).text(officer.fullName ?? "—", 60, oy + 5);
        doc.font("Helvetica").fontSize(9).text(`PASI ID: ${officer.pasiNumber ?? "—"}`, 60, oy + 20);
        doc.text(`Track: ${officer.employmentTrack ?? "—"}  ·  Active Assignments: ${assignments.length}`, 60, oy + 33);
        doc.font("Helvetica-Bold").text("Statement Period:", 280, oy + 5);
        doc.font("Helvetica").text(`${monthName} ${input.year}`, 280, oy + 20);
        doc.moveDown(3);

        // Active assignments
        sectionHeading(doc, "Active Company Assignments");
        tableHeader(doc, ["Company", "CR Number", "Track", "Since"], [180, 100, 80, 135], 50);
        assignments.forEach((a, i) => tableRow(doc, [
          a.companyName ?? "—",
          a.crNumber ?? "—",
          (a.track ?? "—").toUpperCase(),
          a.startDate ? new Date(a.startDate as Date).toLocaleDateString("en-OM") : "—",
        ], [180, 100, 80, 135], 50, i % 2 === 0));
        doc.moveDown(1);

        // Payout breakdown
        sectionHeading(doc, "Payout Breakdown");
        if (payouts.length === 0) {
          doc.fontSize(9).fillColor("#888888").text("No payouts calculated for this period.", 60, doc.y);
          doc.fillColor("#000000");
        } else {
          tableHeader(doc, ["Track", "Gross (OMR)", "Commission %", "Net (OMR)", "Status"], [80, 90, 90, 90, 145], 50);
          payouts.forEach((p, i) => tableRow(doc, [
            (p.employmentTrack ?? "—").toUpperCase(),
            Number(p.grossOmr ?? 0).toFixed(3),
            `${Number(p.commissionPct ?? 0).toFixed(1)}%`,
            Number(p.netOmr ?? 0).toFixed(3),
            (p.status ?? "pending").toUpperCase(),
          ], [80, 90, 90, 90, 145], 50, i % 2 === 0));
        }
        doc.moveDown(1);

        // Net pay box
        doc.rect(50, doc.y, doc.page.width - 100, 36).fill("#1a1a2e");
        doc.fillColor("#e8a020").fontSize(13).font("Helvetica-Bold").text("NET PAYOUT", 60, doc.y - 30);
        doc.fillColor("#ffffff").fontSize(16).text(`OMR ${totalNet.toFixed(3)}`, 0, doc.y - 30, { align: "right", width: doc.page.width - 60 });
        doc.fillColor("#000000").moveDown(2);

        addFooter(doc);
      });

      const key = `reports/officer-payouts/${officer.id}-${input.year}-${input.month}-${Date.now()}.pdf`;
      const { url } = await storagePut(key, pdfBuffer, "application/pdf");
      return { url, filename: `payout-statement-${officer.fullName?.replace(/\s+/g, "-")}-${monthName}-${input.year}.pdf` };
    }),
});
