CREATE TABLE IF NOT EXISTS `attendance_audit` (
  `id` int AUTO_INCREMENT NOT NULL,
  `company_id` int NOT NULL,
  `employee_id` int,
  `hr_attendance_id` int,
  `attendance_record_id` int,
  `correction_id` int,
  `manual_checkin_request_id` int,
  `actor_user_id` int NOT NULL,
  `actor_role` varchar(64),
  `aa_action_type` enum(
    'hr_attendance_create',
    'hr_attendance_update',
    'hr_attendance_delete',
    'correction_approve',
    'correction_reject',
    'manual_checkin_approve',
    'manual_checkin_reject'
  ) NOT NULL,
  `entity_type` varchar(64) NOT NULL,
  `entity_id` int,
  `before_payload` json,
  `after_payload` json,
  `reason` text,
  `aa_source` enum('hr_panel', 'employee_portal', 'admin_panel', 'system') NOT NULL DEFAULT 'hr_panel',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `attendance_audit_id` PRIMARY KEY(`id`),
  INDEX `idx_aa_company` (`company_id`),
  INDEX `idx_aa_actor` (`actor_user_id`),
  INDEX `idx_aa_employee` (`employee_id`),
  INDEX `idx_aa_hr_att` (`hr_attendance_id`),
  INDEX `idx_aa_ar` (`attendance_record_id`),
  INDEX `idx_aa_correction` (`correction_id`),
  INDEX `idx_aa_mcr` (`manual_checkin_request_id`)
);
