-- Phase 3: assignment-centered payroll execution, invoice issuance, traceability (promoter staging → frozen runs).

CREATE TABLE IF NOT EXISTS `promoter_payroll_runs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL,
  `period_start_ymd` DATE NOT NULL,
  `period_end_ymd` DATE NOT NULL,
  `status` ENUM('draft','review_ready','approved','exported','paid','cancelled') NOT NULL DEFAULT 'draft',
  `total_accrued_omr` DECIMAL(14,3) NOT NULL DEFAULT 0,
  `line_count` INT NOT NULL DEFAULT 0,
  `staging_snapshot_json` JSON,
  `warning_ack_json` JSON,
  `export_csv_key` VARCHAR(512),
  `export_csv_url` VARCHAR(1024),
  `exported_at` TIMESTAMP NULL,
  `exported_by_user_id` INT NULL,
  `created_by_user_id` INT NULL,
  `approved_by_user_id` INT NULL,
  `approved_at` TIMESTAMP NULL,
  `paid_at` TIMESTAMP NULL,
  `paid_by_user_id` INT NULL,
  `notes` TEXT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_ppr_company` (`company_id`),
  KEY `idx_ppr_period` (`company_id`, `period_start_ymd`, `period_end_ymd`),
  KEY `idx_ppr_status` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `promoter_payroll_run_lines` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL,
  `run_id` INT NOT NULL,
  `assignment_id` CHAR(36) NOT NULL,
  `employee_id` INT NOT NULL,
  `brand_company_id` INT NOT NULL,
  `client_site_id` INT NULL,
  `readiness_snapshot` VARCHAR(32) NOT NULL,
  `blockers_json` JSON NOT NULL,
  `warnings_json` JSON NOT NULL,
  `payroll_note` TEXT,
  `monthly_salary_basis_omr` DECIMAL(14,3) NULL,
  `period_calendar_days` INT NOT NULL,
  `overlap_days` INT NOT NULL,
  `accrued_pay_omr` DECIMAL(14,3) NOT NULL,
  `staging_row_snapshot_json` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_pprl_run` (`run_id`),
  KEY `idx_pprl_assignment` (`assignment_id`),
  KEY `idx_pprl_company` (`company_id`),
  CONSTRAINT `fk_pprl_run` FOREIGN KEY (`run_id`) REFERENCES `promoter_payroll_runs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `promoter_invoices` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL,
  `invoice_number` VARCHAR(64) NOT NULL,
  `client_company_id` INT NOT NULL,
  `period_start_ymd` DATE NOT NULL,
  `period_end_ymd` DATE NOT NULL,
  `currency_code` VARCHAR(3) NOT NULL DEFAULT 'OMR',
  `subtotal_omr` DECIMAL(14,3) NOT NULL DEFAULT 0,
  `total_omr` DECIMAL(14,3) NOT NULL DEFAULT 0,
  `status` ENUM('draft','review_ready','issued','sent','partially_paid','paid','cancelled') NOT NULL DEFAULT 'draft',
  `monthly_billing_mode` VARCHAR(32) NULL,
  `warning_ack_json` JSON,
  `html_artifact_key` VARCHAR(512),
  `html_artifact_url` VARCHAR(1024),
  `pdf_artifact_key` VARCHAR(512),
  `pdf_artifact_url` VARCHAR(1024),
  `issued_at` TIMESTAMP NULL,
  `issued_by_user_id` INT NULL,
  `created_by_user_id` INT NULL,
  `notes` TEXT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_promoter_inv_number` (`invoice_number`),
  UNIQUE KEY `uq_promoter_inv_period_client` (`company_id`, `client_company_id`, `period_start_ymd`, `period_end_ymd`),
  KEY `idx_pi_company` (`company_id`),
  KEY `idx_pi_status` (`company_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `promoter_invoice_lines` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `company_id` INT NOT NULL,
  `invoice_id` INT NOT NULL,
  `assignment_id` CHAR(36) NOT NULL,
  `employee_id` INT NOT NULL,
  `brand_company_id` INT NOT NULL,
  `client_site_id` INT NULL,
  `billing_model` VARCHAR(32) NULL,
  `billable_units` DECIMAL(18,6) NULL,
  `unit_rate_omr` DECIMAL(14,3) NULL,
  `line_total_omr` DECIMAL(14,3) NOT NULL,
  `monthly_billing_mode` VARCHAR(32) NULL,
  `monthly_proration_sensitive` BOOLEAN NOT NULL DEFAULT 0,
  `monthly_estimate_only` BOOLEAN NOT NULL DEFAULT 0,
  `readiness_snapshot` VARCHAR(32) NOT NULL,
  `blockers_json` JSON NOT NULL,
  `warnings_json` JSON NOT NULL,
  `staging_row_snapshot_json` JSON NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_pil_invoice` (`invoice_id`),
  KEY `idx_pil_assignment` (`assignment_id`),
  CONSTRAINT `fk_pil_invoice` FOREIGN KEY (`invoice_id`) REFERENCES `promoter_invoices` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
