-- =============================================================================
-- Journal backfill: mark 40 previously-applied migrations as known to Drizzle.
-- Generated by: node scripts/generate-backfill.mjs
-- Generated at: 2026-04-26T13:27:15.155Z
--
-- Run against staging first. Verify COUNT = 90 before committing.
-- This is safe to re-run: INSERT IGNORE skips rows that already exist.
-- =============================================================================

START TRANSACTION;

-- Inserting 40 backfill rows (previously missing from journal):
INSERT IGNORE INTO __drizzle_migrations (tag, hash, created_at)
VALUES
  ("0003_phase40_extended_profiles", "a2243db3d85c42019efc155a0e7b1f9e3e86c686e9bd1225912b01053d35809e", NOW()),
  ("0004_hr_letters", "adca8e04b080508bac0ea53d07360ab553bc2eb37c5a77217a77f7e34dd23365", NOW()),
  ("0005_phase43_core_ops", "531add903ead452c34828df0d3dd5c2a6441e90c6bf0087a649927b1f63a8203", NOW()),
  ("0006_attendance_corrections", "4f6eb586b2f0ba25283dd8025d9cf3934468330a6cbcb276b32e184ef011240d", NOW()),
  ("0007_shift_change_requests", "56dfc35b0a6f3e04e9b7e64c1abc6a92d6428ec3a582280bc543405ebd6e74f2", NOW()),
  ("0008_kpi_target_lifecycle", "e9f6ea6b836101149cef67293554a55c4675e0df172089fc4f76d0010624c6a7", NOW()),
  ("0009_employee_tasks_blocked_started", "562f88da30ecc23bb93eb9152929a83ecea46c8cf99ce7b1139bee533f8fd922", NOW()),
  ("0010_employee_tasks_audit_overdue", "46248e54d10c70a94b0bbc246d73fe98b53ed0323a8b940a2db5bf58b5ace457", NOW()),
  ("0011_employee_tasks_checklist_attachments", "a52f63028f09a4103579025791908a9d41fb98777328f2573223f624215d0a78", NOW()),
  ("0012_contract_signature_audit_actor_identity", "1dc20e253dc99044a9ff25d74ab72de2eeea685acf80fe72328923605846f45b", NOW()),
  ("0013_attendance_audit", "ed48d8cb83ad472606636952310d9017a34395c79e85382f4fc111f2df3cca37", NOW()),
  ("0014_attendance_audit_self_service", "0f2ce55c039a181d3e351c7dc2ef1ece89005d3f89911b770f36690d64aad104", NOW()),
  ("0015_attendance_audit_correction_submitted", "bb18046b87da2968980de6b52ce7d316ee66646ae728684c5c5606b9f2b7ab15", NOW()),
  ("0020_agreement_phase3_party_merge", "9dee526d722192a98fd6db5d6ccdf105d00a20ea83f47df1297e114c4d48749d", NOW()),
  ("0021_document_generation_hardening", "d647c10fc27e0b81f36a7ce63fbd28b74e433a48a81360e686c63db01561111f", NOW()),
  ("0022_collection_work_items", "3defc6c07f5feb55889ceecf1bfa471a54d62aebcb15572013bbb7116e5ec9a5", NOW()),
  ("0028_service_quotations_crm_link_columns", "2bea47e6cbb78203576fcbf402d9c3b96b5c80d928a150df72600163c571e576", NOW()),
  ("0029_sanad_office_members_and_roles", "0226c488d134b780423ae0e173735fb34018a3445f79fe1184a4f4959687b062", NOW()),
  ("0035_employee_schedule_groups", "c5dab7ed2a903ae82047b31ab938e2a0c9b45bad88726ed98a59a74fd7b673bd", NOW()),
  ("0048_attendance_operational_issues", "efd35cb53d356da285512e0548eb76f34f6c2b9c22b258f99d30a17832bbdea1", NOW()),
  ("0049_shift_template_break_minutes", "f78cb8caea4bd7735bd0873d70eaf8c7af708ecd6a23398569e6782f40514432", NOW()),
  ("0050_payroll_commission_pay", "ff63dd7b4d9af861009757eb14d0cbacf82fae8cbcd2f07d9cc6ac0d5c5005bc", NOW()),
  ("0051_attendance_site_daily_rate", "dca0a6e551d23486ae8ad19f1a7e6a0f25bfa52dbbdd881d8a48331b3dd3858b", NOW()),
  ("0052_buyer_portal_customer_accounts", "bf3ca66061acf2f1957640eb5a7fddb7250c94e5a2b042a5bbac64cf176d070c", NOW()),
  ("0053_customer_invoice_links", "8c67bc758f301303fe709ced1e1f0cee95a14753f5a2921a8357fb9d7dc59db4", NOW()),
  ("0061_promoter_assignment_operating_phase1", "5e8e293fff4b6cebdf3a24e51114b373b706d6a2cd2071ef606c92bc8380e41d", NOW()),
  ("0062_promoter_assignment_phase1_5", "3b437e6a578bbda4af45552c706138f91a1ec5eda289fd30e32e0476a295da9d", NOW()),
  ("0063_promoter_assignment_phase2_attendance", "192d035b5411329afb4443b6715d89ab6cc4936bbfc0e6dd4408ebfe123c017a", NOW()),
  ("0064_phase3_promoter_financial_execution", "5bd7433667941875956cab4746a0b5070c2ce8af736073e3bb91e7831ba61663", NOW()),
  ("0065_phase3_5_financial_hardening", "a4ca5e410e8174c438d0fb20782faaa62db43c46cd376c379469d81ca12897f2", NOW()),
  ("0066_companies_identity_compliance_commercial", "50328fba1bfeccb1151abf3efa39f4733f7cbbd6d096576897f140364f2f1ef1", NOW()),
  ("0067_employees_payroll_wps_lifecycle_economics", "118e8788bfe918b8064b9c6794eae2375f99e9163c53d259a2d3df7762680701", NOW()),
  ("0068_normalized_compliance_finance_tables", "a173cb8b5c57d027d0cd47b4010f8e575133f3df82a368ee279fc80aeae045a3", NOW()),
  ("0069_drift_fix_3cols", "0349c562bed970b90aa2603c797fd5f8e8b15fcb6b45bba9d09ea6d7f0240203", NOW()),
  ("0071_wps_validation_period_scope", "2402b75c3cf7ce3dacb9d6402d91ac4587bca94cda251733bac6a3390724e843", NOW()),
  ("0076_sanad_invite_token_width", "6b81aac136464d8b42e01fe4568840be4f5b419f1b5cfef50c62ed912ac20929", NOW()),
  ("0077_payroll_run_attendance_preflight_snapshot", "825413c7ffa0a8a909a881340ae20a7d0c99759a3da84503c44ccd4f2f0b5848", NOW()),
  ("0083_attendance_audit_client_portal_source", "9b5100da341215769fd9f38f8a4273e71d6a1e9da94cd32a836debf1d61bd2d6", NOW()),
  ("0084_attendance_billing_candidates", "ce7c8b10c314a58bedffecceb287e7962cb3f30d434b34364cece9963d511c4e", NOW()),
  ("0085_attendance_invoices", "36a1d523082535ebeed0174c1a491ec110eecbd7f51895f767b16ce09f238453", NOW());

-- Verify total count before committing:
SELECT COUNT(*) AS total_migrations FROM __drizzle_migrations;
-- Expected: 90 (was 50, adding 40)

-- If total_migrations is correct:
-- COMMIT;

-- If total_migrations is wrong:
-- ROLLBACK;

-- IMPORTANT: uncomment COMMIT or ROLLBACK before executing!
-- Leaving both commented means the transaction is open until the connection closes.

✓ Generated backfill for 40 migrations
  Old journal size : 50
  New journal size : 90
  Expected DB total: 90
  Output written to: scripts/backfill-migrations.sql

