-- =============================================================================
-- Journal backfill: mark 40 previously-applied migrations as known to Drizzle.
-- Generated by: node scripts/generate-backfill.mjs
-- Generated at: 2026-04-26T14:02:59.934Z
--
-- Table: __drizzle_migrations (schema from scripts/migrate.ts — no tag column)
-- Hash algorithm: SHA-256(segments.join('')) — same as scripts/migrate.ts
--
-- PREFERRED: run `pnpm db:migrate` instead. This script is a fallback for
-- cases where db:migrate fails unexpectedly on the 40 new journal entries.
-- Run against staging first. Verify the SELECT results before committing.
-- INSERT IGNORE makes it safe to re-run.
-- =============================================================================

START TRANSACTION;

-- Inserting 40 backfill rows (previously missing from journal):
-- created_at is stored as milliseconds epoch (matches scripts/migrate.ts behavior).
INSERT IGNORE INTO __drizzle_migrations (hash, created_at)
VALUES
  ("a2243db3d85c42019efc155a0e7b1f9e3e86c686e9bd1225912b01053d35809e", 1774722474835),  -- 0003_phase40_extended_profiles
  ("adca8e04b080508bac0ea53d07360ab553bc2eb37c5a77217a77f7e34dd23365", 1774722475835),  -- 0004_hr_letters
  ("531add903ead452c34828df0d3dd5c2a6441e90c6bf0087a649927b1f63a8203", 1774722476835),  -- 0005_phase43_core_ops
  ("87115c492bd8f6d81b40fadc7e43c8b7a5d0b2600a936646ea7bbbd47cf327f8", 1774722477835),  -- 0006_attendance_corrections
  ("671e1b7675884279439ca68ca9c360cce37088ac546ef1edd9e4b9d791de2508", 1774722478835),  -- 0007_shift_change_requests
  ("e9f6ea6b836101149cef67293554a55c4675e0df172089fc4f76d0010624c6a7", 1774722479835),  -- 0008_kpi_target_lifecycle
  ("562f88da30ecc23bb93eb9152929a83ecea46c8cf99ce7b1139bee533f8fd922", 1774722480835),  -- 0009_employee_tasks_blocked_started
  ("46248e54d10c70a94b0bbc246d73fe98b53ed0323a8b940a2db5bf58b5ace457", 1774722481835),  -- 0010_employee_tasks_audit_overdue
  ("a52f63028f09a4103579025791908a9d41fb98777328f2573223f624215d0a78", 1774722482835),  -- 0011_employee_tasks_checklist_attachments
  ("1dc20e253dc99044a9ff25d74ab72de2eeea685acf80fe72328923605846f45b", 1774722483835),  -- 0012_contract_signature_audit_actor_identity
  ("32955da93b99a5a449805b8607af7a10e038afc4ca6ac199922afb3b6b6ed312", 1774722484835),  -- 0013_attendance_audit
  ("0f2ce55c039a181d3e351c7dc2ef1ece89005d3f89911b770f36690d64aad104", 1774722485835),  -- 0014_attendance_audit_self_service
  ("bb18046b87da2968980de6b52ce7d316ee66646ae728684c5c5606b9f2b7ab15", 1774722486835),  -- 0015_attendance_audit_correction_submitted
  ("9dee526d722192a98fd6db5d6ccdf105d00a20ea83f47df1297e114c4d48749d", 1774722491835),  -- 0020_agreement_phase3_party_merge
  ("d647c10fc27e0b81f36a7ce63fbd28b74e433a48a81360e686c63db01561111f", 1774722492835),  -- 0021_document_generation_hardening
  ("3defc6c07f5feb55889ceecf1bfa471a54d62aebcb15572013bbb7116e5ec9a5", 1774722493835),  -- 0022_collection_work_items
  ("2bea47e6cbb78203576fcbf402d9c3b96b5c80d928a150df72600163c571e576", 1774722499835),  -- 0028_service_quotations_crm_link_columns
  ("0226c488d134b780423ae0e173735fb34018a3445f79fe1184a4f4959687b062", 1774722500835),  -- 0029_sanad_office_members_and_roles
  ("2768241faa5f5d768bf72aca7acb45925faa86a3218962513de835417a2a2981", 1774722506835),  -- 0035_employee_schedule_groups
  ("0a9b10b1c77f79379df30cb1273283dc44015ab7f5839c10ee69400f9c6d25a3", 1774722519835),  -- 0048_attendance_operational_issues
  ("f78cb8caea4bd7735bd0873d70eaf8c7af708ecd6a23398569e6782f40514432", 1774722520835),  -- 0049_shift_template_break_minutes
  ("ff63dd7b4d9af861009757eb14d0cbacf82fae8cbcd2f07d9cc6ac0d5c5005bc", 1774722521835),  -- 0050_payroll_commission_pay
  ("dca0a6e551d23486ae8ad19f1a7e6a0f25bfa52dbbdd881d8a48331b3dd3858b", 1774722522835),  -- 0051_attendance_site_daily_rate
  ("bf3ca66061acf2f1957640eb5a7fddb7250c94e5a2b042a5bbac64cf176d070c", 1774722523835),  -- 0052_buyer_portal_customer_accounts
  ("8c67bc758f301303fe709ced1e1f0cee95a14753f5a2921a8357fb9d7dc59db4", 1774722524835),  -- 0053_customer_invoice_links
  ("5e8e293fff4b6cebdf3a24e51114b373b706d6a2cd2071ef606c92bc8380e41d", 1774722532835),  -- 0061_promoter_assignment_operating_phase1
  ("3b437e6a578bbda4af45552c706138f91a1ec5eda289fd30e32e0476a295da9d", 1774722533835),  -- 0062_promoter_assignment_phase1_5
  ("192d035b5411329afb4443b6715d89ab6cc4936bbfc0e6dd4408ebfe123c017a", 1774722534835),  -- 0063_promoter_assignment_phase2_attendance
  ("5bd7433667941875956cab4746a0b5070c2ce8af736073e3bb91e7831ba61663", 1774722535835),  -- 0064_phase3_promoter_financial_execution
  ("a4ca5e410e8174c438d0fb20782faaa62db43c46cd376c379469d81ca12897f2", 1774722536835),  -- 0065_phase3_5_financial_hardening
  ("50328fba1bfeccb1151abf3efa39f4733f7cbbd6d096576897f140364f2f1ef1", 1774722537835),  -- 0066_companies_identity_compliance_commercial
  ("118e8788bfe918b8064b9c6794eae2375f99e9163c53d259a2d3df7762680701", 1774722538835),  -- 0067_employees_payroll_wps_lifecycle_economics
  ("a173cb8b5c57d027d0cd47b4010f8e575133f3df82a368ee279fc80aeae045a3", 1774722539835),  -- 0068_normalized_compliance_finance_tables
  ("549ecfdd276997f08c76c184146e5afb97b04a7a2c4b6facec8daaffba14dfc8", 1774722540835),  -- 0069_drift_fix_3cols
  ("2402b75c3cf7ce3dacb9d6402d91ac4587bca94cda251733bac6a3390724e843", 1774722542835),  -- 0071_wps_validation_period_scope
  ("6b81aac136464d8b42e01fe4568840be4f5b419f1b5cfef50c62ed912ac20929", 1774722547835),  -- 0076_sanad_invite_token_width
  ("825413c7ffa0a8a909a881340ae20a7d0c99759a3da84503c44ccd4f2f0b5848", 1774722548835),  -- 0077_payroll_run_attendance_preflight_snapshot
  ("9b5100da341215769fd9f38f8a4273e71d6a1e9da94cd32a836debf1d61bd2d6", 1774722554835),  -- 0083_attendance_audit_client_portal_source
  ("ce7c8b10c314a58bedffecceb287e7962cb3f30d434b34364cece9963d511c4e", 1774722555835),  -- 0084_attendance_billing_candidates
  ("36a1d523082535ebeed0174c1a491ec110eecbd7f51895f767b16ce09f238453", 1774722556835);  -- 0085_attendance_invoices

-- ── Verify BEFORE committing ────────────────────────────────────────────────

-- 1. Total count must match expected:
SELECT COUNT(*) AS total_migrations FROM __drizzle_migrations;
--    Expected: 90 (was 50, adding 40)

-- 2. Spot-check: confirm at least 3 of the new hashes are present:
SELECT COUNT(*) AS spot_check FROM __drizzle_migrations
  WHERE hash IN ("a2243db3d85c42019efc155a0e7b1f9e3e86c686e9bd1225912b01053d35809e", "adca8e04b080508bac0ea53d07360ab553bc2eb37c5a77217a77f7e34dd23365", "531add903ead452c34828df0d3dd5c2a6441e90c6bf0087a649927b1f63a8203");
--    Expected: 3 (if 0, INSERT IGNORE skipped all rows — hashes may already exist or mismatch)

-- 3. Confirm no unexpected extra rows (guards against double-backfill):
SELECT COUNT(*) AS total_migrations FROM __drizzle_migrations;
--    Still expected: 90

-- 4. Verify newly-inserted rows by epoch range
--    (created_at values for new entries: 1774722474835 – 1774722556835)
SELECT COUNT(*) AS in_range FROM __drizzle_migrations
  WHERE created_at BETWEEN 1774722474835 AND 1774722556835;
--    Expected: 40 (or more if prior migrations had similar timestamps)

-- ── Commit or roll back ──────────────────────────────────────────────────────

-- If all checks above look correct:
-- COMMIT;

-- If anything looks wrong:
-- ROLLBACK;

-- IMPORTANT: uncomment exactly one of COMMIT or ROLLBACK before executing.
-- Leaving both commented means the transaction stays open until the connection closes.

✓ Generated backfill for 40 migrations
  Old journal size : 50
  New journal size : 90
  Expected DB total: 90
  Hash algorithm   : SHA-256(breakpoint-stripped content) — matches scripts/migrate.ts
  Output           : scripts/backfill-migrations.sql

